### ISSUE TITLE
Test specs reference a nonexistent value

### ISSUE THREAD

**Issue by ross-u** [ironhack-labs/lab-dom-pizza-builder#815]
When tests are run, the following error is thrown:

```
    Evaluation failed: ReferenceError: state is not defined

      at __puppeteer_evaluation_script__:1:8
      at ExecutionContext._evaluateInternal (node_modules/puppeteer/src/common/ExecutionContext.ts:275:13)
      at ExecutionContext.evaluate (node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
      at Object.<anonymous> (tests/pizza-builder.spec.js:24:19)
 ```

**Comment by MarcoSantonastasi** [comment]
@ross-u I reproduced the issue but inconsistently so I cannot be sure this is a definitive

 fix.
I propose a solution here because I cannot access the ironhack labs to commit.

Issue on line 12:
https://github.com/ironhack-labs/lab-dom-pizza-builder/blob/1c72182ce5137b5d5dcaae11bd3764b869e0b99d/tests/pizza-builder.spec.js#L12

Line 12 is `const getPageState = () => page.evaluate(() => state);`

should be `const getPageState = async () => await page.evaluate(() => state);`

in fact `getPageState(`) is always called with await, therefore it should return a promise explicitly
